# -*- coding: utf-8 -*-
"""Contrast Enhancment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ctxtR8DuDhVatKlJBZEXSKV__gNwwK8

120707025 Caesar Noor
"""

# Commented out IPython magic to ensure Python compatibility.

# import library
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import cv2
import matplotlib.image as mpimg
from skimage import data
from google.colab.patches import cv2_imshow

# membaca citra input
image = cv2.imread("Buffa.jpg")

# Penerapan Histogram Equalization (HE)
image_equalized = cv2.equalizeHist(image)

# menerapkan metode CLAHE
clahe = cv2.createCLAHE(clipLimit=2, tileGridSize=(8,8))

# mengaplikasikan CLAHE ke citra asli
image_clahe = clahe.apply(image)

# menerapan metode Contrast Stretching (CS)

# membuat Array kosong untuk mengisi output akhir
image_cs = np.zeros((image.shape[0],image.shape[1]),dtype = 'uint8')

# mengaplikasikan Min-Max Contras
min = np.min(image)
max = np.max(image)

# Rumus metode CS
for i in range(image.shape[0]):
    for j in range(image.shape[1]):
        image_cs[i,j] = 255*(image[i,j]-min)/(max-min)

# penerapan metode perkalian Constanta 
copyBuffa = image.copy().astype(float)

# variable gambar
m1,n1 = copyBuffa.shape
output1 = np.empty([m1, n1])

# menentukan baris kolom gambar
for baris in range(0, m1-1):
    for kolom in range(0, n1-1):
        a1 = baris
        b1 = kolom
        output1[a1, b1] = copyBuffa[baris, kolom] * 1.9

# mengatur ukuran dan revolusi gambar
fig, axes = plt.subplots(5, 2, figsize=(20, 20))
ax = axes.ravel()

# menampilkan gambar Input dan histogramnya 
ax[0].imshow(image, cmap=plt.cm.gray)
ax[0].set_title("Citra Input")
ax[1].hist(image.ravel(), bins=256)
ax[1].set_title('Histogram Input')

# menampilkan gambar output HE dan histogramnya
ax[2].imshow(image_equalized, cmap=plt.cm.gray)
ax[2].set_title("Citra Output HE")
ax[3].hist(image_equalized.ravel(), bins=256)
ax[3].set_title('Histogram Output HE Method')

# menampilkan gambar output CS dan histogramnya 
ax[4].imshow(image_cs, cmap=plt.cm.gray)
ax[4].set_title("Citra Output CS")
ax[5].hist(image_cs.ravel(), bins=256)
ax[5].set_title('Histogram Output CS Method')

# menampilkan gambar grayscale CLAHE dan histogramnya 
ax[6].imshow(image_clahe, cmap=plt.cm.gray)
ax[6].set_title("Citra Grayscale CLAHE")
ax[7].hist(image_clahe.ravel(), bins=256)
ax[7].set_title('Histogram Output CLAHE Method')

# menampilkan gambar grayscale perkalian Konstanta dan histogramnya 
ax[8].imshow(output1, cmap=plt.cm.gray)
ax[8].set_title("Citra Grayscale Perkalian Konstanta")
ax[9].hist(output1.ravel(), bins=256)
ax[9].set_title('Histogram Output Perkalian Konstanta Method')

fig.tight_layout()