# -*- coding: utf-8 -*-
"""Filter Rerata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HRN_vfwT80KdE0Ae2VTv1U7WpfCoYGfk

1207070025 Caesar noor
"""

# Commented out IPython magic to ensure Python compatibility.

# impor library
import matplotlib.pyplot as plt
# %matplotlib inline

from skimage import data
from skimage.io import imread
from skimage.color import rgb2gray 
import numpy as np

# membaca dan memeberi label gambar ber noise
citra1 = imread(fname="mobil.tif")
citra2 = imread(fname="boneka2.tif")

# memeberikan statistik bentuk citra
print('Shape citra 1 : ', citra1.shape)
print('Shape citra 2 : ', citra2.shape)

# memberikan ukuran pada citra
fig, axes = plt.subplots(1, 2, figsize=(10, 10))
ax = axes.ravel()

# menampilkan dan memberikan title pada citra
ax[0].imshow(citra1, cmap = 'gray')
ax[0].set_title("Citra 1")
ax[1].imshow(citra2, cmap = 'gray')
ax[1].set_title("Citra 2")

# menyalingambar dan memberinya type
copyCitra1 = citra1.copy().astype(float)
copyCitra2 = citra2.copy().astype(float)

# memberikan variable pertama
m1,n1 = copyCitra1.shape
output1 = np.empty([m1, n1])

# memeberikan variabel kedua
m2,n2 = copyCitra2.shape
output2 = np.empty([m2, n2])

# menampilkan statistik nilai gambar
print('Shape copy citra 1 : ', copyCitra1.shape)
print('Shape output citra 1 : ', output1.shape)

# menampilkan statistik nilai variable gambar pertama
print('m1 : ',m1)
print('n1 : ',n1)
print()

# menampilkan statustuk nilai variable gamabr kedua
print('Shape copy citra 2 : ', copyCitra2.shape)
print('Shape output citra 3 : ', output2.shape)
print('m2 : ',m2)
print('n2 : ',n2)
print()

# rumus baris dan kolom untuk gambar pertama
for baris in range(0, m1-1):
    for kolom in range(0, n1-1):
        a1 = baris
        b1 = kolom
        jumlah = copyCitra1[a1-1, b1-1] + copyCitra1[a1-1, b1] + copyCitra1[a1-1, b1-1] + \
                 copyCitra1[a1, b1-1] + copyCitra1[a1, b1] + copyCitra1[a1, b1+1] + \
                 copyCitra1[a1+1, b1-1] + copyCitra1[a1+1, b1] + copyCitra1[a1+1, b1+1];  
        output1[a1, b1] = (1/9 * jumlah)

# rumus baris dan kolom untuk gambar kedua
for baris1 in range(0, m2-1):
    for kolom1 in range(0, n2-1):
        a1 = baris1
        b1 = kolom1
        jumlah = copyCitra2[a1-1, b1-1] + copyCitra2[a1-1, b1] + copyCitra2[a1-1, b1-1] + \
                 copyCitra2[a1, b1-1] + copyCitra2[a1, b1] + copyCitra2[a1, b1+1] + \
                 copyCitra2[a1+1, b1-1] + copyCitra2[a1+1, b1] + copyCitra2[a1+1, b1+1];  
        output2[a1, b1] = (1/9 * jumlah)

# mengatur ukuran gambar keluaran
fig, axes = plt.subplots(2, 2, figsize=(10, 10))
ax = axes.ravel()

# menampilkan dan memberikan judul pada gambar asli pertama
ax[0].imshow(citra1, cmap = 'gray')
ax[0].set_title("Input Citra 1")

# menampilkan dan memberikan judul pada gambar asli kedua
ax[1].imshow(citra2, cmap = 'gray')
ax[1].set_title("Input Citra 1")

# menampilkan dan memberikan judul pada gambar keluaran pertama
ax[2].imshow(output1, cmap = 'gray')
ax[2].set_title("Output Citra 1")

# menampilkan dan memberikan judul pada gambar keluaran kedua 
ax[3].imshow(output2, cmap = 'gray')
ax[3].set_title("Output Citra 2")