# -*- coding: utf-8 -*-
"""Filter median.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d9lKYo1eEPYDkEK8P4pSQwwEmC1apoK6

1207070025 Caesar Noor
"""

# Commented out IPython magic to ensure Python compatibility.

# impor library
import matplotlib.pyplot as plt
# %matplotlib inline

from skimage import data
from skimage.io import imread
from skimage.color import rgb2gray 
import numpy as np

# membaca dan memberi label pada gambar input
citra1 = imread(fname="mobil.tif")
citra2 = imread(fname="boneka2.tif")

# memberikan bentuk pada gambar
print('Shape citra 1 : ', citra1.shape)
print('Shape citra 1 : ', citra2.shape)

# mengatur ukuran gambar
fig, axes = plt.subplots(1, 2, figsize=(10, 10))
ax = axes.ravel()

# menampilkan dan memberikan judul pada gambar asli pertama dan kedua 
ax[0].imshow(citra1, cmap = 'gray')
ax[0].set_title("Citra 1")
ax[1].imshow(citra2, cmap = 'gray')
ax[1].set_title("Citra 2")

# menyalin dan memeberi label gambar pertama dan kedua
copyCitra1 = citra1.copy()
copyCitra2 = citra2.copy()

# memberikan variable keluaran pada gambar pertama 
m1,n1 = copyCitra1.shape
output1 = np.empty([m1, n1])

# memberikan variable keluaran pada gambar kedua 
m2,n2 = copyCitra2.shape
output2 = np.empty([m2, n2])

# memberikan bentuk pada salinan dan keluaran gambar pertama 
print('Shape copy citra 1 : ', copyCitra1.shape)
print('Shape output citra 1 : ', output1.shape)

# variable gambar pertama 
print('m1 : ',m1)
print('n1 : ',n1)
print()

# memberikan bentuk pada salinan dan keluaran gambar kedua 
print('Shape copy citra 2 : ', copyCitra2.shape)
print('Shape output citra 3 : ', output2.shape)

# variable gambar kedua 
print('m2 : ',m2)
print('n2 : ',n2)
print()

# rumus fungsi proses filter median untuk gambar pertama 
for baris in range(0, m1-1):
    for kolom in range(0, n1-1):
        a1 = baris
        b1 = kolom
        dataA = [copyCitra1[a1-1, b1-1], copyCitra1[a1-1, b1], copyCitra1[a1-1, b1+1], \
              copyCitra1[a1, b1-1], copyCitra1[a1, b1], copyCitra1[a1, b1+1], \
              copyCitra1[a1+1, b1-1], copyCitra1[a1+1, b1], copyCitra1[a1+1, b1+1]]
        
        # Urutkan
        for i in range(1, 8):
            for j in range(i, 9):
                if dataA[i] > dataA[j]:
                    tmpA = dataA[i];
                    dataA[i] = dataA[j];
                    dataA[j]= tmpA;
        
        output1[a1, b1] = dataA[5]

# rumus fungsi proses filter median untuk gambar kedua
for baris in range(0, m2-1):
    for kolom in range(0, n2-1):
        a1 = baris
        b1 = kolom
        dataA = [copyCitra2[a1-1, b1-1], copyCitra2[a1-1, b1], copyCitra2[a1-1, b1+1], \
              copyCitra2[a1, b1-1], copyCitra2[a1, b1], copyCitra2[a1, b1+1], \
              copyCitra2[a1+1, b1-1], copyCitra2[a1+1, b1], copyCitra2[a1+1, b1+1]]
        
        # Urutkan
        for i in range(1, 8):
            for j in range(i, 9):
                if dataA[i] > dataA[j]:
                    tmpA = dataA[i];
                    dataA[i] = dataA[j];
                    dataA[j]= tmpA;
        
        output2[a1, b1] = dataA[5]

# mengatur ukuran gambar keluaran pertama dan kedua
fig, axes = plt.subplots(2, 2, figsize=(10, 10))
ax = axes.ravel()

# menampilkan dan memberikan judul pada gambar input pertama
ax[0].imshow(citra1, cmap = 'gray')
ax[0].set_title("Input Citra 1")

# menampilkan dan memberikan judul pada gambar input kedua 
ax[1].imshow(citra2, cmap = 'gray')
ax[1].set_title("Input Citra 1")

# menampilkan dan memberikan judul pada gambar keluaran pertama 
ax[2].imshow(output1, cmap = 'gray')
ax[2].set_title("Output Citra 1")

# menampilkan dan memberikan judul pada gambar keluaran kedua 
ax[3].imshow(output2, cmap = 'gray')
ax[3].set_title("Output Citra 2")