# -*- coding: utf-8 -*-
"""Gray level.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G5V5a1gKg2DVtSV9ik9XXWcZ2jml5zWc

1207070025 Caesar Noor
"""

# Commented out IPython magic to ensure Python compatibility.

# mengimpor library
import cv2
import numpy as np
from skimage import data
import matplotlib.pyplot as plt
# %matplotlib inline
from google.colab.patches import cv2_imshow

# membaca gambar input
img = cv2.imread("F.png")

# memberikan fungsi baris dan kolom
row, column = img.shape

# memberikan revolusi dan type gambar 
img1 = np.zeros((row,column),dtype = 'uint8')
 
# jangkauan minimal dan maksimal
min_range = 10
max_range = 60
 
# rumus gray level gambar
for i in range(row):
    for j in range(column):
        if img[i,j]>min_range and img[i,j]<max_range:
            img1[i,j] = 255
        else:
            img1[i,j] = 0

# mengatur ukuran pada gambar
fig, axes = plt.subplots(2, 2, figsize=(12, 12))
ax = axes.ravel()

# menampilkan gambar imput dan histogramnya 
ax[0].imshow(img, cmap=plt.cm.gray)
ax[0].set_title("Citra Input")
ax[1].hist(img.ravel(), bins=256)
ax[1].set_title('Histogram Input')

# menampilkan gambar output dan histogramnya 
ax[2].imshow(img1, cmap=plt.cm.gray)
ax[2].set_title("Citra Output")
ax[3].hist(img1.ravel(), bins=256)
ax[3].set_title('Histogram Output')