# -*- coding: utf-8 -*-
"""Praktikum6 Flip Gambar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12eF0rClsPGFl1rdkfipd2Q-AS4kSrXmX

Caesar Noor 1207070025
"""

# import library
import numpy as np
import imageio
import matplotlib.pyplot as plt

# memasukkan dan membaca gambar yg dipakai
img = imageio.imread("Tf.png")

# memberikan bentuk, resolusi, dan type pada gambar 
img_height = img.shape[0]
img_width = img.shape[1]
img_channel = img.shape[2]
img_type = img.dtype

# memberikan fungsi variable untuk flip gambar horizontal dan vertikal
img_flip_horizontal = np.zeros(img.shape, img_type)
img_flip_vertical = np.zeros(img.shape, img_type)

# perhitungan flip gambar horizontal
for y in range(0, img_height):
    for x in range(0, img_width):
        for c in range(0, img_channel):
            img_flip_horizontal[y][x][c] = img[y][img_width-1-x][c]

# perhitungan flip gambar vertikal
for y in range(0, img_height):
    for x in range(0, img_width):
        for c in range(0, img_channel):
            img_flip_vertical[y][x][c] = img[img_height-1-y][x][c]

# menampilkan hasil gambar yg telah di flip

# flip horizontal
plt.imshow(img_flip_horizontal)
plt.title("Flip Horizontal")
plt.show()

# flip vertical
plt.imshow(img_flip_vertical)
plt.title("Flip Vertical")
plt.show()